#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieservice
  namespace: Sep6jcah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieservice
  template:
    metadata:
      labels:
        app: movieservice
    spec:
      containers:
        - name: movieservice
          image: europe-docker.pkg.dev/sep6-jcah/sep6-jcah/client:latest
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
          ports:
          - containerPort: 80

---

#Service
apiVersion: v1
kind: Service
metadata:
  name: movieservice
  namespace: Sep6jcah
spec:
  selector:
    app: movieservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
